### ISSUE TITLE
Add author to template for meta

### ISSUE THREAD

**Issue by ViachaslauKabak** [lean-delivery/cookiecutter-ansible-role#9]
##### SUMMARY
there is no   author: "Lean Delivery team <team@lean-delivery.com>" in meta/main.yml template

##### ISSUE TYPE
lint fails cause there id no author in meta file

##### EXPECTED RESULTS
author set in template for meta/main.yml
during role creation there is a step to set author

##### ACTUAL RESULTS
no author in meta/main.yml

**Comment by vutkin** [comment]
doesn't reproduced
